<a href="https://colab.research.google.com/github/vladgap/LLC/blob/main/Rotem%20LLC%20simulation%209.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [156]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go
from plotly.subplots import make_subplots
from sklearn import preprocessing
import matplotlib.pyplot as plt

from scipy import optimize

In [2]:
pip install MLNN

  Preparing metadata (setup.py) ... done
  Created wheel for MLNN: filename=MLNN-2.1-py3-none-any.whl size=7866 sha256=48e20f04fd3a4abb3839ad3c4ca23de86e43fc02a964f6790324515ba8525179
  Stored in directory: /root/.cache/pip/wheels/9e/e0/20/d5af76160e4e218d06f2277dc88a9dab41cb0b6e1d4221a58b
Successfully built MLNN


In [3]:
from MLNN import*

In [4]:
import LLC_4_1 as LLC
# import https://github.com/vladgap/LLC/LLC_4_1.py?raw=true as LLC

In [5]:
def CopyPasteToArray(a):
  if a.startswith('\n'):
    b=a[1:]
  else:
    b=a
  if b.endswith('\n'):
    b=b[:-1]
  c=b.replace('\t',',')
  d=c.split('\n')
  f=[]
  for e in d:
    if e.replace(',','').replace('.','').isdigit(): # only digits no letters
      f.append(list(eval(e)))
    else:
      f.append(e.split(','))
  return f

# EQUIL data

## EQUIL_rotem_lit1
lit data with NN model (7 hidden sigmoids)

### Equilibrium literature data

In [6]:
data1=pd.DataFrame(data=[
[63.5,	1.3,	42.4,	15.0],
[58.7,	1.2,	36.9,	13.8],
[52.0, 1.0,	27.7,	11.8],
[45.5,	1.0,	18.9,	9.6],
[39.1,	1.4,	10.2,	8.3],
[31.5,	1.5,	5.1,	8.8],
[22.9,	2.0,	2.3,	9.0],
[12.6,	2.2,	0.90,	9.3],
[6.3,	2.4,	0.45,	9.45],
[0.01,	2.6,	0.01,	9.6],
],
columns=['H3PO4_aq', 'solvent_aq', 'H3PO4_org', 'water_org'])

In [7]:
data1.head()

H3PO4_aq  solvent_aq  H3PO4_org  water_org
0      63.5         1.3       42.4       15.0
1      58.7         1.2       36.9       13.8
2      52.0         1.0       27.7       11.8
3      45.5         1.0       18.9        9.6
4      39.1         1.4       10.2        8.3

In [8]:
fig1=go.Figure()
[fig1.add_trace(go.Scatter(x=data1.H3PO4_aq, y=data1[data1.columns[i]], name=data1.columns[i])) for i in range(1,4)]
fig1.update_layout(title='', width=1200, height=600,)
fig1.show()

In [9]:
X1=np.array(data1)[:,[0]]
T1=np.array(data1)[:,[1,2,3]]

### Model
"Model for Rotem LLC simulation 1"

In [10]:
scaler_X1 = preprocessing.StandardScaler()
scaler_T1 = preprocessing.StandardScaler()
scaler_X1.mean_, scaler_X1.scale_ = [33.211], [21.13387066]
scaler_T1.mean_, scaler_T1.scale_ = [1.66,  14.486, 10.465], [0.56071383, 15.23739033,  2.16703138]

bp1=VectorBackProp(layers=[1,7,3], hidden_activation = 'sigmoid')
manual_best_weights_for_now2=[[[-4.215621245080982,
   -8.235086763118087,
   -1.6251342150606451,
   -6.9206357615871035,
   -3.4092427169369826,
   -7.4263402914028775,
   -3.7003458539301977]],
 [[0.8764395040443358,
   3.9145850159876945,
   -1.5013585830931442,
   -1.194371163565281,
   4.118411550251139,
   5.892242255497829,
   -6.755593628941706]],
 [[-2.6609909047049918, -0.44480776958732143, 1.9256391063013463],
  [2.566022222516618, -0.5042582093932455, -1.432212975592254],
  [1.405004033981333, -0.2988952466228391, 0.5807591718257896],
  [2.0692859230668117, -0.0780871568942863, -0.5145373287488922],
  [-0.7989625307881565, -1.957459884661486, -2.8991426864622065],
  [-0.5821795598385298, -0.22284877970127598, -0.9077232625087237],
  [1.619488070885094, 0.03697105802710269, 0.008613201857731975]],
 [[-0.4010006364699687, 2.4687577407660806, 2.995012357373033]]]
bp1.import_weights(manual_best_weights_for_now2)

In [11]:
class EQUIL_rotem_lit1: # literature data for pentanol 25C
# gets xout [%solvent_aq, %H3PO4_aq]
# calc xout , yout [%water_org, %H3PO4_org]

    def __init__(self, x):
        x=np.array(x, dtype=float) # [[%solv, %H3PO4], [%solv, %H3PO4], [%solv, %H3PO4], ...]
        # the model predicts %solvent_aq, %H3PO4_aq, %water_org from %H3PO4_aq
        # x[:,[1]] is column vector of %H3PO4_aq [[1], [2], ...]
        pred=scaler_T1.inverse_transform(bp1.run(scaler_X1.transform(x[:,[1]])))
        # prediction is column vector of lists [%solvent_aq, %H3PO4_aq, %water_org]

        self.xout = np.array([pred[:,0], x[:,1]]).T # [[%solvent_aq, %H3PO4_aq], ...]
        self.yout = np.array([pred[:,2], pred[:,1]]).T # [[%water_org, %H3PO4_org], ...]

## EQUIL_rotem_washing1
Rotem solvent, estimation by polynoms

In [12]:
class EQUIL_rotem_washing1: # prepared using purified and washed solvents
# gets xout [%solvent_aq, %H3PO4_aq]
# calc xout , yout [%water_org, %H3PO4_org]

    def __init__(self, x):
        x=np.array(x, dtype=float) # [[%solv, %H3PO4], [%solv, %H3PO4], [%solv, %H3PO4], ...]
        y=np.zeros_like(x)
        # x[:,[1]] is column vector of %H3PO4_aq [[1], [2], ...]
        # y = A + B*x + C*x^2 + D*x^3

        # %solvent_aq
        D,C,B,A = -3.78E-06,8.15E-04,- 5.73E-02,2.45E+00
        x[:,0] = A + B*x[:,1] + C*x[:,1]**2 + D*x[:,1]**3

        # %water_org
        D,C,B,A = 4.45E-05,- 1.56E-03,- 1.84E-02,7.58E+00
        y[:,0] = A + B*x[:,1] + C*x[:,1]**2 + D*x[:,1]**3

        # %H3PO4_org
        # D,C,B,A = 2.00E-04,- 4.86E-03,7.07E-02,2.73E-02
        # y[:,1] = A + B*x[:,1] + C*x[:,1]**2 + D*x[:,1]**3
        G,F,E,D,C,B,A = -1.97E-09,2.02E-07,- 2.95E-06,- 3.83E-05,2.60E-03,2.38E-02,1.70E-02
        y[:,1] = A + B*x[:,1] + C*x[:,1]**2 + D*x[:,1]**3 + E*x[:,1]**4 + F*x[:,1]**5 + G*x[:,1]**6

        self.xout = np.array([x[:,0], x[:,1]]).T # [[%solvent_aq, %H3PO4_aq], ...]
        self.yout = np.array([y[:,0], y[:,1]]).T # [[%water_org, %H3PO4_org], ...]

In [13]:
# EQUIL_rotem_washing1([[2,20],[1.5,30],[1.3,40]]).xout

## EQUIL_rotem_washing2
Rotem solvent, full profile, sulfate

In [14]:
data=CopyPasteToArray('''
H3PO4_aq	SO4_aq	H3PO4_org	water_org	solvent_aq	SO4_org
4.15	0.147	0.0733	9.6	2.5	0.0626
14.9	0.0806	0.359	9.5	2.2	0.0852
28.6	0.0329	1.68	9.3	1.9	0.0787
45.7	0.0106	8.31	8.5	1.6	0.0664
48.2	0.0078	10.7	8.5	1.3	0.0631
49.4	0.0058	12.2	8.7	1.0	0.0641
''')
# data
# data2=pd.DataFrame(data, columns=['H3PO4_aq',	'SO4_aq',	'H3PO4_org',	'water_org',	'solvent_aq',	'SO4_org'])
data2=pd.DataFrame(data[1:], columns=data[0])
data2

H3PO4_aq  SO4_aq  H3PO4_org  water_org  solvent_aq  SO4_org
0      4.15  0.1470     0.0733        9.6         2.5   0.0626
1     14.90  0.0806     0.3590        9.5         2.2   0.0852
2     28.60  0.0329     1.6800        9.3         1.9   0.0787
3     45.70  0.0106     8.3100        8.5         1.6   0.0664
4     48.20  0.0078    10.7000        8.5         1.3   0.0631
5     49.40  0.0058    12.2000        8.7         1.0   0.0641

In [15]:
X2=np.array(data2)[:,[0,1]]
T2_1=np.array(data2)[:,[2]]
T2_2=np.array(data2)[:,[3]]
T2_3=np.array(data2)[:,[4]]
T2_4=np.array(data2)[:,[5]]

scaler_X2 = preprocessing.StandardScaler().fit(X2)
scaler_T2_1 = preprocessing.StandardScaler().fit(T2_1)
scaler_T2_2 = preprocessing.StandardScaler().fit(T2_2)
scaler_T2_3 = preprocessing.StandardScaler().fit(T2_3)
scaler_T2_4 = preprocessing.StandardScaler().fit(T2_4)

X_sc2 = scaler_X2.transform(X2)
# T_sc2_1 = scaler_T2_1.transform(T2_1)
# T_sc2_2 = scaler_T2_1.transform(T2_2)
# T_sc2_3 = scaler_T2_1.transform(T2_3)
# T_sc2_4 = scaler_T2_1.transform(T2_4)

In [16]:
class EQUIL_rotem_washing2: # from full profile, sulfate
# gets xout [%solvent_aq, %H3PO4_aq, %SO4_aq]
# calc xout , yout [%water_org, %H3PO4_org, %SO4_org]

    def __init__(self, x):
        x=np.array(x, dtype=float) # [[%solv, %H3PO4, %SO4], [%solv, %H3PO4, %SO4], [%solv, %H3PO4, %SO4], ...]
        # the model predicts H3PO4_org, water_org ,solvent_aq, SO4_org
        # x[:,[1]] is column vector of %H3PO4_aq [[1], [2], ...]
        # x[:,[2]] is for %SO4_aq

        # H3PO4_org
        bp2_1=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights2_1=[[[0.1735491429461148, 1.8140938189194906],
  [-0.6530409129171293, -0.6441814583921941]],
 [[0.7411897128053353, -1.2033881701371891]],
 [[0.3516552639162472], [1.6547118904069311]],
 [[-1.0860308848681413]]]
        bp2_1.import_weights(manual_weights2_1)
        predics2_1=abs(scaler_T2_1.inverse_transform(bp2_1.run(scaler_X2.transform(x[:,[1,2]]))))

        # water_org
        bp2_2=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights2_2=[[[-1.356083366626272, 2.1006456906712234],
  [-0.6309805208401018, -0.5374527149916659]],
 [[1.0515374304634164, -2.3182953246087115]],
 [[1.4841383017903245], [3.153523627853289]],
 [[-1.7074908699001965]]]
        bp2_2.import_weights(manual_weights2_2)
        predics2_2=abs(scaler_T2_2.inverse_transform(bp2_2.run(scaler_X2.transform(x[:,[1,2]]))))

        # solvent_aq
        bp2_3=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights2_3=[[[2.0994823528593702, -1.2293957752203057],
  [-0.6972915446623457, 0.5216771334283966]],
 [[-2.3459563115354527, 1.775004898861346]],
 [[-3.1726827033207408], [0.4025651395234753]],
 [[-0.4638947231253712]]]
        bp2_3.import_weights(manual_weights2_3)
        predics2_3=abs(scaler_T2_3.inverse_transform(bp2_3.run(scaler_X2.transform(x[:,[1,2]]))))

        # SO4_org
        bp2_4=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights2_4=[[[-2.7308241499437758, 1.8373933992350313],
  [-2.021898044039464, -0.8845457922101067]],
 [[1.0694417308325381, 0.08920200363835196]],
 [[2.7835653102552724], [1.6175935763910405]],
 [[-4.969235753353272]]]
        bp2_4.import_weights(manual_weights2_4)
        predics2_4=abs(scaler_T2_4.inverse_transform(bp2_4.run(scaler_X2.transform(x[:,[1,2]]))))

        self.xout = np.array([predics2_3[:,0], x[:,1], x[:,2]]).T # [[%solvent_aq, %H3PO4_aq, %SO4_aq], ...]
        self.yout = np.array([predics2_2[:,0], predics2_1[:,0], predics2_4[:,0]]).T # [[%water_org, %H3PO4_org, %SO4_org], ...]

        print (self.yout, self.xout)

## EQUIL_rotem_washing3
ניסויי הפרדה עם ממס מטוהר

In [17]:
# X3=np.array(data3)[:,[0,1]]
# T3_1=np.array(data3)[:,[2]]
# T3_2=np.array(data3)[:,[3]]
# T3_3=np.array(data3)[:,[4]]
# T3_4=np.array(data3)[:,[5]]

# scaler_X3 = preprocessing.StandardScaler().fit(X3)
# scaler_T3_1 = preprocessing.StandardScaler().fit(T3_1)
# scaler_T3_2 = preprocessing.StandardScaler().fit(T3_2)
# scaler_T3_3 = preprocessing.StandardScaler().fit(T3_3)
# scaler_T3_4 = preprocessing.StandardScaler().fit(T3_4)

# X_sc3 = scaler_X3.transform(X3)

In [18]:
Xscale=[21.97576471,  0.05575882], [15.2853469,   0.05047379]
Tscale=[1.89941176, 11.19176471,  1.4,         0.02921412], [2.40216868, 1.27085536, 0.17875386, 0.01997862]

scaler_X3 = preprocessing.StandardScaler().fit([[0,0]])
scaler_X3_2 = preprocessing.StandardScaler().fit([[0,0]]) # מים בקלה חושבו רק על נתונים "טובים
scaler_T3_1 = preprocessing.StandardScaler().fit([[0]])
scaler_T3_2 = preprocessing.StandardScaler().fit([[0]])
scaler_T3_3 = preprocessing.StandardScaler().fit([[0]])
scaler_T3_4 = preprocessing.StandardScaler().fit([[0]])

scaler_X3.mean_, scaler_X3.scale_ = Xscale[0], Xscale[1]
scaler_X3_2.mean_, scaler_X3_2.scale_ = [27.03608333,  0.0474    ], [14.68499343,  0.04213688] # מים בקלה חושבו רק על נתונים "טובים
scaler_T3_1.mean_, scaler_T3_1.scale_=[Tscale[0][0]], [Tscale[1][0]]
# scaler_T3_2.mean_, scaler_T3_2.scale_=[Tscale[0][1]], [Tscale[1][1]]
scaler_T3_2.mean_, scaler_T3_2.scale_=[10.81], [1.3091664] # מים בקלה חושבו רק על נתונים "טובים
scaler_T3_3.mean_, scaler_T3_3.scale_=[Tscale[0][2]], [Tscale[1][2]]
scaler_T3_4.mean_, scaler_T3_4.scale_=[Tscale[0][3]], [Tscale[1][3]]

In [19]:
class EQUIL_rotem_washing3: # ניסויי הפרדה עם ממס מטוהר
# gets xout [%solvent_aq, %H3PO4_aq, %SO4_aq]
# calc xout , yout [%water_org, %H3PO4_org, %SO4_org]

    def __init__(self, x):
        x=np.array(x, dtype=float) # [[%solv, %H3PO4, %SO4], [%solv, %H3PO4, %SO4], [%solv, %H3PO4, %SO4], ...]
        # the model predicts H3PO4_org, water_org ,solvent_aq, SO4_org
        # x[:,[1]] is column vector of %H3PO4_aq [[1], [2], ...]
        # x[:,[2]] is for %SO4_aq

        # H3PO4_org
        bp3_1=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights3_1=[[[-0.2328053114817587, 1.4197258515721494],
  [-0.013739923476318716, -0.009509632921841494]],
 [[1.5848282259786703, -0.9625030403646567]],
 [[-1.3007118041663503], [1.5725920350068667]],
 [[1.717]]]
        bp3_1.import_weights(manual_weights3_1)
        predics3_1=scaler_T3_1.inverse_transform(bp3_1.run(scaler_X3.transform(x[:,[1,2]])))

        # water_org
        bp3_2=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights3_2=[[[0.3909002105371126, -0.8406267181665068],
  [-0.4530958444599508, 0.704664998208326]],
 [[-0.09671769242746425, 0.7927475123043677]],
 [[0.48441213405704675], [-0.7676170242577324]],
 [[0.6435152247205708]]]
        bp3_2.import_weights(manual_weights3_2)
        predics3_2=scaler_T3_2.inverse_transform(bp3_2.run(scaler_X3_2.transform(x[:,[1,2]]))) # מים בקלה חושבו רק על נתונים "טובים
        # predics3_2=np.ones([len(x),1])*12 #  תוצאות אנליטיות לא מדויקות. לקחתי 12 באופן גורף

        # solvent_aq
        bp3_3=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights3_3=[[[0.6217022345240342, 2.8386999598609814],
  [-0.6968938452576019, 5.596033242601742]],
 [[2.7109590937198265, 0.22193377952697202]],
 [[-0.9372090292368469], [-0.33293100862641933]],
 [[3.277263990359097]]]
        bp3_3.import_weights(manual_weights3_3)
        predics3_3=scaler_T3_3.inverse_transform(bp3_3.run(scaler_X3.transform(x[:,[1,2]])))

        # SO4_org
        bp3_4=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights3_4=[[[-0.10168260750729177, 1.5507975795954547],
  [-0.02429351337425621, -5.794943503077378e-05]],
 [[1.5556257229985646, -0.978368082003519]],
 [[-1.3219817921544152], [1.6394490601340548]],
 [[1.5742747334295601]]]
        bp3_4.import_weights(manual_weights3_4)
        predics3_4=scaler_T3_4.inverse_transform(bp3_4.run(scaler_X3.transform(x[:,[1,2]])))

        self.xout = np.array([predics3_3[:,0], x[:,1], x[:,2]]).T # [[%solvent_aq, %H3PO4_aq, %SO4_aq], ...]
        self.yout = np.array([predics3_2[:,0], predics3_1[:,0], predics3_4[:,0]]).T # [[%water_org, %H3PO4_org, %SO4_org], ...]

        # print (self.yout, self.xout)

In [20]:
class EQUIL_rotem_washing3_2: # ניסויי הפרדה עם ממס מטוהר
# gets xout [%solvent_aq, %H3PO4_aq, %SO4_aq]
# calc xout , yout [%water_org, %H3PO4_org, %SO4_org]

    def __init__(self, x):
        x=np.array(x, dtype=float) # [[%solv, %H3PO4, %SO4], [%solv, %H3PO4, %SO4], [%solv, %H3PO4, %SO4], ...]
        # the model predicts H3PO4_org, water_org ,solvent_aq, SO4_org
        # x[:,[1]] is column vector of %H3PO4_aq [[1], [2], ...]
        # x[:,[2]] is for %SO4_aq

        # H3PO4_org
        bp3_1=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights3_1=[[[-0.2328053114817587, 1.4197258515721494],
  [-0.013739923476318716, -0.009509632921841494]],
 [[1.5848282259786703, -0.9625030403646567]],
 [[-1.3007118041663503], [1.5725920350068667]],
 [[1.717]]]
        bp3_1.import_weights(manual_weights3_1)
        predics3_1=abs(scaler_T3_1.inverse_transform(bp3_1.run(scaler_X3.transform(x[:,[1,2]]))))

        # water_org
        bp3_2=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights3_2=[[[0.3909002105371126, -0.8406267181665068],
  [-0.4530958444599508, 0.704664998208326]],
 [[-0.09671769242746425, 0.7927475123043677]],
 [[0.48441213405704675], [-0.7676170242577324]],
 [[0.6435152247205708]]]
        bp3_2.import_weights(manual_weights3_2)
        # predics3_2=abs(scaler_T3_2.inverse_transform(bp3_2.run(scaler_X3_2.transform(x[:,[1,2]])))) # מים בקלה חושבו רק על נתונים "טובים
        predics3_2=np.ones([len(x),1])*12 #  תוצאות אנליטיות לא מדויקות. לקחתי 12 באופן גורף

        # solvent_aq
        bp3_3=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights3_3=[[[0.6217022345240342, 2.8386999598609814],
  [-0.6968938452576019, 5.596033242601742]],
 [[2.7109590937198265, 0.22193377952697202]],
 [[-0.9372090292368469], [-0.33293100862641933]],
 [[3.277263990359097]]]
        bp3_3.import_weights(manual_weights3_3)
        predics3_3=abs(scaler_T3_3.inverse_transform(bp3_3.run(scaler_X3.transform(x[:,[1,2]]))))

        # SO4_org
        bp3_4=VectorBackProp(layers=[2,2,1], hidden_activation = 'prelu')
        manual_weights3_4=[[[-0.10168260750729177, 1.5507975795954547],
  [-0.02429351337425621, -5.794943503077378e-05]],
 [[1.5556257229985646, -0.978368082003519]],
 [[-1.3219817921544152], [1.6394490601340548]],
 [[1.5742747334295601]]]
        bp3_4.import_weights(manual_weights3_4)
        predics3_4=abs(scaler_T3_4.inverse_transform(bp3_4.run(scaler_X3.transform(x[:,[1,2]]))))

        self.xout = np.array([predics3_3[:,0], x[:,1], x[:,2]]).T # [[%solvent_aq, %H3PO4_aq, %SO4_aq], ...]
        self.yout = np.array([predics3_2[:,0], predics3_1[:,0], predics3_4[:,0]]).T # [[%water_org, %H3PO4_org, %SO4_org], ...]

        # print (self.yout, self.xout)

# Cases

## Literature data

### 1 - Washing



In [21]:
bat1_2=LLC.Battery(stages_num=5, Oin=90, Ain=29, yin=[5,12], xin=[5,0], EQUIL=EQUIL_rotem_lit1, convergence=5e-4, eff=[1, 0.7], entrainment_perc_in=[2,5], entrainment_comp_in=[[5,5],[10,10]], entrainment_perc_out=[3,4])
# bat1_2=LLC.Battery(4, 87.6, 112.4, [0, 0], [0, 32.56], EQUIL=EQUIL_rotem_lit1, convergence=5e-4, eff=.7, entrainment_perc_out=10)

In [22]:
bat1_2.runs

35

In [23]:
table1_2=LLC.BatteryTableFull(bat1_2).data

Stage 1    Stage 2    Stage 3    Stage 4  \
Org in, ton/hr             90.000000  89.055359  85.475686  83.948464   
y1 in, %                    5.000000   8.829622   9.079322   9.354564   
y2 in, %                   12.000000   6.974399   3.352100   1.529652   
Aq in, ton/hr              34.382667  30.833850  29.321083  28.640994   
x1 in, %                    2.075036   2.268582   2.424578   2.529920   
x2 in, %                   19.948914  10.447329   4.783224   1.865826   
Org out, ton/hr            89.055213  85.474791  83.948421  83.262549   
y1 out, %                   8.829647   9.079543   9.354583   9.494752   
y2 out, %                   6.974221   3.350772   1.529553   0.667935   
Aq out, ton/hr             34.452985  34.379990  30.833663  29.320314   
x1 out, %                   1.531734   2.075206   2.268598   2.424691   
x2 out, %                  30.939276  19.941437  10.446634   4.779801   
K2 [aq/org]                 6.418516  11.092200  13.957484  16.005919   
aq in org_in, %             2.000000   3.000000   3.000000   3.000000   
org in aq_in, %             4.000000   4.000000   4.000000   4.000000   
aq in org_out, %            3.000000   3.000000   3.000000   3.000000   
org in aq_out, %            4.000000   4.000000   4.000000   4.000000   
aq in org_in, ton/hr        1.800000   2.671661   2.564271   2.518454   
org in aq_in, ton/hr        1.375307   1.233354   1.172843   1.145640   
aq in org_out, ton/hr       2.671656   2.564244   2.518453   2.497876   
org in aq_out, ton/hr       1.378119   1.375200   1.233347   1.172813   
aq contrain in Oin - x1%    5.000000   1.531703   2.075036   2.268582   
aq contrain in Oin - x2%    5.000000  30.939836  19.948914  10.447329   
org contrain in Ain - y1%   9.079322   9.354564   9.494674   9.558546   
org contrain in Ain - y2%   3.352100   1.529652   0.668417   0.281863   

                             Stage 5  
Org in, ton/hr             83.262505  
y1 in, %                    9.494674  
y2 in, %                    0.668417  
Aq in, ton/hr              29.000000  
x1 in, %                    5.000000  
x2 in, %                    0.000000  
Org out, ton/hr            83.906581  
y1 out, %                   9.558549  
y2 out, %                   0.281837  
Aq out, ton/hr             28.640963  
x1 out, %                   2.529926  
x2 out, %                   1.865679  
K2 [aq/org]                16.061385  
aq in org_in, %             3.000000  
org in aq_in, %             5.000000  
aq in org_out, %            3.000000  
org in aq_out, %            4.000000  
aq in org_in, ton/hr        2.497875  
org in aq_in, ton/hr        1.450000  
aq in org_out, ton/hr       2.517197  
org in aq_out, ton/hr       1.145639  
aq contrain in Oin - x1%    2.424578  
aq contrain in Oin - x2%    4.783224  
org contrain in Ain - y1%  10.000000  
org contrain in Ain - y2%  10.000000

In [24]:
bat=bat1_2
fig1_3 = go.Figure()
n=1 #H3PO4
fig1_3.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_tag_list[:,n], name='Equilibrium', marker_color='black'))
fig1_3.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_list[:,n], name='Efficiency', marker_color='blue'))
fig1_3.add_trace(go.Scatter(x=np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])), y=np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])), mode = "markers+lines+text",
                          text= ['({:.2f},{:.2f})'.format(a,b) for a,b in zip(np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])),np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])))],
                          textposition ='bottom center', name='Operation', marker_color='green'))
fig1_3.update_xaxes(title_text="x, %")#, range=[0.5, 2])
fig1_3.update_yaxes(title_text="y, %")#, range=[0.5, 2])
fig1_3.update_layout(title='', width=1200, height=600,)
fig1_3.show()

In [25]:
fig1_4=go.Figure()
current_data = data1
current_table = table1_2
[fig1_4.add_trace(go.Scatter(x=current_data.H3PO4_aq, y=current_data[current_data.columns[i]], name=current_data.columns[i])) for i in range(1,4)]
fig1_4.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='x1 out, %'].values[0]))
fig1_4.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='y2 out, %'].values[0]))
fig1_4.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='y1 out, %'].values[0]))

# fig1_4.update_xaxes(title_text="x, %", range=[20, 40])
# fig1_4.update_yaxes(title_text="y, %", range=[0, 15])
fig1_4.update_layout(title='', width=1200, height=600,)
fig1_4.show()

### 2 - Extraction

In [26]:
bat2=LLC.Battery(stages_num=7, Oin=90, Ain=29, yin=[5,0], xin=[0,40], EQUIL=EQUIL_rotem_lit1, convergence=5e-4, eff=[[.8, 1], [0.5, .8], [.6,.9]])

In [27]:
bat2.runs

38

In [28]:
bat2.eff

array([[1. , 1. ],
       [1. , 0.8],
       [1. , 0.9],
       [1. , 1. ],
       [1. , 1. ],
       [1. , 1. ],
       [1. , 1. ]])

In [29]:
table2=LLC.BatteryTableFull(bat2).data

Stage 1    Stage 2    Stage 3    Stage 4  \
Org in, ton/hr             90.000000  96.473211  96.995114  97.591662   
y1 in, %                    5.000000   8.991353   8.936158   8.913425   
y2 in, %                    0.000000   2.343352   2.895783   3.477733   
Aq in, ton/hr              24.303520  24.832050  25.420661  26.121458   
x1 in, %                    1.846572   1.742477   1.628782   1.519116   
x2 in, %                   26.076255  27.717279  29.376141  31.174464   
Org out, ton/hr            96.473586  96.992375  97.593864  98.283709   
y1 out, %                   8.991297   8.936323   8.913326   8.883276   
y2 out, %                   2.343821   2.892832   3.479975   4.148719   
Aq out, ton/hr             17.829934  24.312885  24.821911  25.429411   
x1 out, %                   1.982812   1.847227   1.742008   1.629795   
x2 out, %                  23.178525  26.064965  27.724203  29.361104   
K2 [aq/org]                 9.889203   8.601726   7.820901   7.077149   
aq in org_in, %             0.000000   0.000000   0.000000   0.000000   
org in aq_in, %             0.000000   0.000000   0.000000   0.000000   
aq in org_out, %            0.000000   0.000000   0.000000   0.000000   
org in aq_out, %            0.000000   0.000000   0.000000   0.000000   
aq in org_in, ton/hr        0.000000   0.000000   0.000000   0.000000   
org in aq_in, ton/hr        0.000000   0.000000   0.000000   0.000000   
aq in org_out, ton/hr       0.000000   0.000000   0.000000   0.000000   
org in aq_out, ton/hr       0.000000   0.000000   0.000000   0.000000   
aq contrain in Oin - x1%    0.000000   1.982898   1.846572   1.742477   
aq contrain in Oin - x2%    0.000000  23.176168  26.076255  27.717279   
org contrain in Ain - y1%   8.936158   8.913425   8.882908   8.818593   
org contrain in Ain - y2%   2.895783   3.477733   4.154708   4.927815   

                             Stage 5     Stage 6     Stage 7  
Org in, ton/hr             98.289728   99.065594  100.080908  
y1 in, %                    8.882908    8.818593    8.686241  
y2 in, %                    4.154708    4.927815    5.937057  
Aq in, ton/hr              26.893674   27.928541   29.000000  
x1 in, %                    1.440582    1.414597    0.000000  
x2 in, %                   33.199446   35.744126   40.000000  
Org out, ton/hr            99.070893  100.077211  101.186610  
y1 out, %                   8.818035    8.687748    8.456033  
y2 out, %                   4.933070    5.927017    7.477362  
Aq out, ton/hr             26.112510   26.916924   27.894298  
x1 out, %                   1.518521    1.441046    1.414599  
x2 out, %                  31.185853   33.180776   35.757000  
K2 [aq/org]                 6.321794    5.598225    4.782034  
aq in org_in, %             0.000000    0.000000    0.000000  
org in aq_in, %             0.000000    0.000000    0.000000  
aq in org_out, %            0.000000    0.000000    0.000000  
org in aq_out, %            0.000000    0.000000    0.000000  
aq in org_in, ton/hr        0.000000    0.000000    0.000000  
org in aq_in, ton/hr        0.000000    0.000000    0.000000  
aq in org_out, ton/hr       0.000000    0.000000    0.000000  
org in aq_out, ton/hr       0.000000    0.000000    0.000000  
aq contrain in Oin - x1%    1.628782    1.519116    1.440582  
aq contrain in Oin - x2%   29.376141   31.174464   33.199446  
org contrain in Ain - y1%   8.686241    8.457185    0.000000  
org contrain in Ain - y2%   5.937057    7.468639    0.000000

In [30]:
bat=bat2
fig2_1 = go.Figure()
n=1 #H3PO4
fig2_1.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_tag_list[:,n], name='Equilibrium', marker_color='black'))
fig2_1.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_list[:,n], name='Efficiency', marker_color='blue'))
fig2_1.add_trace(go.Scatter(x=np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])), y=np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])), mode = "markers+lines+text",
                          text= ['({:.2f},{:.2f})'.format(a,b) for a,b in zip(np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])),np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])))],
                          textposition ='bottom center', name='Operation', marker_color='green'))
fig2_1.update_xaxes(title_text="x, %")#, range=[0.5, 2])
fig2_1.update_yaxes(title_text="y, %")#, range=[0.5, 2])
fig2_1.update_layout(title='', width=1200, height=600,)
fig2_1.show()

In [31]:
fig2_2=go.Figure()
current_data = data1
current_table = table2
[fig2_2.add_trace(go.Scatter(x=current_data.H3PO4_aq, y=current_data[current_data.columns[i]], name=current_data.columns[i])) for i in range(1,4)]
fig2_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='x1 out, %'].values[0]))
fig2_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='y2 out, %'].values[0]))
fig2_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='y1 out, %'].values[0]))

# fig2_2.update_xaxes(title_text="x, %", range=[20, 40])
# fig2_2.update_yaxes(title_text="y, %", range=[0, 15])
fig2_2.update_layout(title='', width=1200, height=600,)
fig2_2.show()

## Washing data
Rotem solvent, estimation by polynoms

### 3 - Washing1

In [32]:
bat3=LLC.Battery(stages_num=7, Oin=204, Ain=33.3, yin=[7.7,14.4], xin=[0,0], EQUIL=EQUIL_rotem_washing1)#, convergence=5e-4, eff=[1, 0.7], entrainment_perc_in=[2,5], entrainment_comp_in=[[5,5],[10,10]], entrainment_perc_out=[3,4])

In [33]:
bat3.runs

141

In [34]:
table3=LLC.BatteryTable(bat3).data

Stage 1     Stage 2     Stage 3     Stage 4     Stage 5  \
Org in, ton/hr   204.000000  195.342174  183.280373  174.327927  172.269404   
y1 in, %           7.700000    7.577914    7.051886    6.835793    7.295850   
y2 in, %          14.400000   11.104978    6.308415    2.044015    0.446296   
Aq in, ton/hr     57.516594   45.446384   36.500004   34.438744   34.231179   
x1 in, %           1.245967    1.459202    1.968008    2.330954    2.432270   
x2 in, %          37.669252   25.367315    9.686259    2.142208    0.310800   
Org out, ton/hr  195.344416  183.275916  174.329792  172.269154  172.061607   
y1 out, %          7.578015    7.051702    6.835725    7.296082    7.533819   
y2 out, %         11.105811    6.306478    2.045084    0.445905    0.079546   
Aq out, ton/hr    66.172178   57.512642   45.450586   36.497517   34.438977   
x1 out, %          1.182006    1.246009    1.459066    1.968283    2.330861   
x2 out, %         44.355524   37.665812   25.373147    9.679808    2.143945   

                    Stage 6     Stage 7  
Org in, ton/hr   172.061591  172.039690  
y1 in, %           7.533862    7.574132  
y2 in, %           0.079486    0.024647  
Aq in, ton/hr     34.209255   33.300000  
x1 in, %           2.448012    0.000000  
x2 in, %           0.034716    0.000000  
Org out, ton/hr  172.039701  171.130433  
y1 out, %          7.574140    7.579359  
y2 out, %          0.024637    0.017830  
Aq out, ton/hr    34.231145   34.209257  
x1 out, %          2.432292    2.448010  
x2 out, %          0.310408    0.034755

In [35]:
bat=bat3
fig3 = go.Figure()
n=1 #H3PO4
fig3.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_tag_list[:,n], name='Equilibrium', marker_color='black'))
fig3.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_list[:,n], name='Efficiency', marker_color='blue'))
fig3.add_trace(go.Scatter(x=np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])), y=np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])), mode = "markers+lines+text",
                          text= ['({:.2f},{:.2f})'.format(a,b) for a,b in zip(np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])),np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])))],
                          textposition ='bottom center', name='Operation', marker_color='green'))
fig3.update_xaxes(title_text="x, %")#, range=[0.5, 2])
fig3.update_yaxes(title_text="y, %")#, range=[0.5, 2])
fig3.update_layout(title='', width=1200, height=600,)
fig3.show()

In [36]:
fig3_2=go.Figure()
# current_data = data1
current_table = table3
# [fig1_4.add_trace(go.Scatter(x=current_data.H3PO4_aq, y=current_data[current_data.columns[i]], name=current_data.columns[i])) for i in range(1,4)]
fig3_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='x1 out, %'].values[0]))
fig3_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='y2 out, %'].values[0]))
fig3_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='y1 out, %'].values[0]))

# fig3_2.update_xaxes(title_text="x, %", range=[20, 40])
# fig3_2.update_yaxes(title_text="y, %", range=[0, 15])
fig3_2.update_layout(title='', width=1200, height=600,)
fig3_2.show()

### 4 - Washing2

In [37]:
bat4=LLC.Battery(stages_num=7, Oin=204, Ain=33.3, yin=[7.7,14.4], xin=[0,0], EQUIL=EQUIL_rotem_washing1, convergence=5e-4, eff=[1, 0.9], entrainment_perc_in=[2,0], entrainment_comp_in=[[5,5],[0,0]], entrainment_perc_out=[3,4])

In [38]:
bat4.runs

13

In [39]:
table4=LLC.BatteryTableFull(bat4).data

Stage 1     Stage 2     Stage 3     Stage 4  \
Org in, ton/hr             204.000000  197.476924  192.054619  184.980696   
y1 in, %                     7.700000    7.639709    7.413024    7.107238   
y2 in, %                    14.400000   11.892679    9.921331    7.179893   
Aq in, ton/hr               59.968484   54.876756   47.942418   40.551758   
x1 in, %                     1.195117    1.234671    1.330063    1.567682   
x2 in, %                    42.683779   38.641698   31.823762   21.122384   
Org out, ton/hr            197.489684  192.098515  185.012627  177.569184   
y1 out, %                    7.640308    7.414765    7.108539    6.846031   
y2 out, %                   11.897083    9.937810    7.192845    3.994027   
Aq out, ton/hr              64.454662   60.203450   54.916699   47.892005   
x1 out, %                    1.177906    1.194958    1.234429    1.332783   
x2 out, %                   44.930281   42.702750   38.663222   31.663637   
K2 [aq/org]                  3.866972    4.393015    5.611759    8.698700   
aq in org_in, %              2.000000    3.000000    3.000000    3.000000   
org in aq_in, %              4.000000    4.000000    4.000000    4.000000   
aq in org_out, %             3.000000    3.000000    3.000000    3.000000   
org in aq_out, %             4.000000    4.000000    4.000000    4.000000   
aq in org_in, ton/hr         4.080000    5.924308    5.761639    5.549421   
org in aq_in, ton/hr         2.398739    2.195070    1.917697    1.622070   
aq in org_out, ton/hr        5.924691    5.762955    5.550379    5.327076   
org in aq_out, ton/hr        2.578186    2.408138    2.196668    1.915680   
aq contrain in Oin - x1%     5.000000    1.177944    1.195117    1.234671   
aq contrain in Oin - x2%     5.000000   44.924884   42.683779   38.641698   
org contrain in Ain - y1%    7.413024    7.107238    6.848766    6.914708   
org contrain in Ain - y2%    9.921331    7.179893    4.041803    1.668367   

                              Stage 5     Stage 6     Stage 7  
Org in, ton/hr             177.693848  173.096470  171.797120  
y1 in, %                     6.848766    6.914708    7.272929  
y2 in, %                     4.041803    1.668367    0.608861  
Aq in, ton/hr               36.028255   34.633532   33.300000  
x1 in, %                     1.941366    2.272553    0.000000  
x2 in, %                    10.318621    3.244250    0.000000  
Org out, ton/hr            173.104408  171.776807  169.156745  
y1 out, %                    6.913954    7.285448    7.505317  
y2 out, %                    1.672885    0.584278    0.169015  
Aq out, ton/hr              40.573566   35.940507   34.634218  
x1 out, %                    1.566830    1.955823    2.272382  
x2 out, %                   21.152908    9.973839    3.247534  
K2 [aq/org]                 15.005549   21.503497   27.030571  
aq in org_in, %              3.000000    3.000000    3.000000  
org in aq_in, %              4.000000    4.000000    0.000000  
aq in org_out, %             3.000000    3.000000    3.000000  
org in aq_out, %             4.000000    4.000000    4.000000  
aq in org_in, ton/hr         5.330815    5.192894    5.153914  
org in aq_in, ton/hr         1.441130    1.385341    0.000000  
aq in org_out, ton/hr        5.193132    5.153304    5.074702  
org in aq_out, ton/hr        1.622943    1.437620    1.385369  
aq contrain in Oin - x1%     1.330063    1.567682    1.941366  
aq contrain in Oin - x2%    31.823762   21.122384   10.318621  
org contrain in Ain - y1%    7.272929    7.505406    0.000000  
org contrain in Ain - y2%    0.608861    0.168822    0.000000

In [40]:
bat=bat4
fig4 = go.Figure()
n=1 #H3PO4
fig4.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_tag_list[:,n], name='Equilibrium', marker_color='black'))
fig4.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_list[:,n], name='Efficiency', marker_color='blue'))
fig4.add_trace(go.Scatter(x=np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])), y=np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])), mode = "markers+lines+text",
                          text= ['({:.2f},{:.2f})'.format(a,b) for a,b in zip(np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])),np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])))],
                          textposition ='bottom center', name='Operation', marker_color='green'))
fig4.update_xaxes(title_text="x, %")#, range=[0.5, 2])
fig4.update_yaxes(title_text="y, %")#, range=[0.5, 2])
fig4.update_layout(title='Operation Data', width=1200, height=600,)
fig4.show()

In [41]:
fig4_2=go.Figure()
# current_data = data1
current_table = table4
fig4_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='x1 out, %'].values[0]))
fig4_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='y2 out, %'].values[0]))
fig4_2.add_trace(go.Scatter(x=current_table.loc[current_table.index=='x2 out, %'].values[0], y=current_table.loc[current_table.index=='y1 out, %'].values[0]))

# fig4_2.update_xaxes(title_text="x, %", range=[20, 40])
# fig4_2.update_yaxes(title_text="y, %", range=[0, 15])
fig4_2.update_layout(title='Equilibrium Data', width=1200, height=600,)
fig4_2.show()

## Rotem washing with sulfate

### 5 - Washing1

In [42]:
EQUIL_rotem_washing2([[2.2,14.9,.0806]]).yout

[[9.56542351 0.35871824 0.08520132]] [[ 2.2011776 14.9        0.0806   ]]


array([[9.56542351, 0.35871824, 0.08520132]])

In [78]:
test1 = LLC.Stage(90, 29, [10, 14, .07], [2, 0.1, .02], EQUIL_rotem_washing2, eff=1)#, entrainment_perc=[1,2,3,4], entrainment_comp_in=[[10,10],[5,5]], convergence=1E-4)

[[9.46653099 0.24737723 0.07612773]] [[ 2.19935864 15.84801765  0.0863365 ]]
[[9.39613205 2.03387074 0.09890064]] [[1.87066035e+00 2.82119226e+01 1.68273031e-02]]
[[10.08467975  3.54737652  0.18614079]] [[ 1.7537705  26.23665403 -0.05223446]]
[[8.22536903 9.20724111 0.05845868]] [[1.55596228e+00 4.94449510e+01 2.92414692e-02]]
[[9.58472547 1.87652887 0.10774695]] [[1.93899998e+00 2.40879688e+01 2.04689708e-02]]
[[9.38953099 1.60760867 0.08915488]] [[ 1.94403543 25.65121271  0.03373056]]
[[9.16982768 1.16600286 0.06629933]] [[ 1.97408083 26.54040093  0.05413683]]
[[9.00913961 0.91051604 0.05052035]] [[ 1.98421109 27.61361808  0.06639933]]
[[9.04981814 0.93004127 0.05388785]] [[ 1.98956985 27.05905272  0.06507602]]
[[9.03516254 0.91462003 0.05255816]] [[ 1.98911091 27.20630747  0.06588359]]
[[9.02787834 0.90237085 0.05183361]] [[ 1.98968729 27.250775    0.06646579]]
[[8.96500589 0.97891448 0.04811076]] [[ 1.96267725 28.77652377  0.06430156]]
[[9.06274314 0.92028267 0.05473617]] [[ 1.9940

In [44]:
test1.runs

10

In [45]:
test1.output()

Oout= 74.5042053393592
yout= [8.60822308 0.09877921 0.02661528]
yout_tag= [8.60822308 0.09877921 0.02661528]  %water_org_equilib, %solubles_equilib
Aout= 44.49579466064079
xout= [ 2.06758444 28.21705147  0.11005343]
equilibrium efficiency= [1. 1. 1.]
error= [4.11296949e-05 5.50745531e-05 6.80630206e-05]
convergence= [-0.00040428 -0.00022316 -0.00016548]


In [46]:
test1 = LLC.Stage(90, 29, [8.60822308, 0.09877921, 0.02661528], [2.06758444, 28.21705147, 0.11005343], EQUIL_rotem_washing2, eff=1)#, entrainment_perc=[1,2,3,4], entrainment_comp_in=[[10,10],[5,5]], convergence=1E-4)

[[9.40587212 0.08828243 0.06697643]] [[ 2.24355622 14.81172832  0.10004056]]
[[9.64682125 2.83556223 0.13886871]] [[ 1.78411875e+00  2.90630819e+01 -1.82035537e-02]]
[[8.21751925 0.08034712 0.02647194]] [[ 2.37666577 25.232862    0.23555299]]
[[8.21268012 0.05489456 0.02621698]] [[ 2.80349145 26.46953754  0.44614586]]
[[8.74664907 0.11174503 0.02662841]] [[ 2.06769155 26.97713024  0.10147547]]
[[8.60768029 0.09853519 0.02661446]] [[ 2.07167602 28.0758201   0.11100685]]
[[8.60564232 0.09871973 0.02661485]] [[ 2.06858194 28.20448409  0.11043802]]
[[8.60879365 0.09878278 0.02661534]] [[ 2.06752461 28.2140926   0.11000452]]
[[8.60794753 0.09877988 0.02661526]] [[ 2.06757328 28.21991049  0.11006804]]


In [47]:
bat5_1=LLC.Battery(stages_num=4, Oin=90, Ain=29, yin=[8.60822308, 1, 0.05], xin=[2.06758444, 30, 0.3], EQUIL=EQUIL_rotem_washing2)

[[8.21653274 0.07325848 0.02649106]] [[ 2.49550578 17.11028579  0.23526643]]
[[8.21542165 0.07060956 0.02631295]] [[ 2.53998164 31.47867061  0.35630376]]
[[8.21539376 0.07041787 0.02631317]] [[ 2.54319538 31.28743445  0.35649378]]
[[8.21539538 0.07041956 0.02631351]] [[ 2.543167   31.25688796  0.35626778]]
[[8.21539487 0.07041688 0.02631348]] [[ 2.54321195 31.25704348  0.35629013]]
[[8.21539496 0.07041739 0.02631349]] [[ 2.54320338 31.25703412  0.35628601]]
[[8.21653274 0.07325848 0.02649106]] [[ 2.49550578 17.11028579  0.23526643]]
[[8.21542165 0.07060956 0.02631295]] [[ 2.53998164 31.47867061  0.35630376]]
[[8.21539376 0.07041787 0.02631317]] [[ 2.54319538 31.28743445  0.35649378]]
[[8.21539538 0.07041956 0.02631351]] [[ 2.543167   31.25688796  0.35626778]]
[[8.21539487 0.07041688 0.02631348]] [[ 2.54321195 31.25704348  0.35629013]]
[[8.21539496 0.07041739 0.02631349]] [[ 2.54320338 31.25703412  0.35628601]]
[[8.21653274 0.07325848 0.02649106]] [[ 2.49550578 17.11028579  0.23526643]]

In [48]:
bat5_1.runs

6

In [49]:
table5=LLC.BatteryTable(bat5_1).data

Stage 1    Stage 2    Stage 3    Stage 4
Org in, ton/hr   90.000000  88.607990  88.615281  88.615270
y1 in, %          8.608223   8.215397   8.216589   8.216587
y2 in, %          1.000000   0.070425   0.076451   0.076442
y3 in, %          0.050000   0.026314   0.026386   0.026385
Aq in, ton/hr    29.114540  29.121741  29.121729  29.000000
x1 in, %          2.442020   2.442172   2.442171   2.067584
x2 in, %         29.864179  29.874934  29.874918  30.000000
x3 in, %          0.298710   0.298857   0.298856   0.300000
Org out, ton/hr  88.607990  88.615281  88.615270  88.493540
y1 out, %         8.215397   8.216589   8.216587   8.216587
y2 out, %         0.070425   0.076451   0.076442   0.076442
y3 out, %         0.026314   0.026386   0.026385   0.026385
Aq out, ton/hr   30.506550  29.114449  29.121741  29.121730
x1 out, %         2.543082   2.442013   2.442172   2.442171
x2 out, %        31.247113  29.864055  29.874934  29.874918
x3 out, %         0.356160   0.298706   0.298857   0.298856

In [50]:
bat=bat5_1
fig5 = go.Figure()
n=1 #H3PO4
fig5.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_tag_list[:,n], name='Equilibrium', marker_color='black'))
fig5.add_trace(go.Scatter(x=bat.xout_list[:,n], y=bat.yout_list[:,n], name='Efficiency', marker_color='blue'))
fig5.add_trace(go.Scatter(x=np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])), y=np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])), mode = "markers+lines+text",
                          text= ['({:.2f},{:.2f})'.format(a,b) for a,b in zip(np.concatenate((bat.xout_list[:,n], [bat.xin_list[-1,n]])),np.concatenate((bat.yin_list[:,n], [bat.yout_list[-1,n]])))],
                          textposition ='bottom center', name='Operation', marker_color='green'))
fig5.update_xaxes(title_text="x, %")#, range=[0.5, 2])
fig5.update_yaxes(title_text="y, %")#, range=[0.5, 2])
fig5.update_layout(title='Operation Data', width=1200, height=600,)
fig5.show()

In [51]:
fig_equil2 = make_subplots(rows=2, cols=2, subplot_titles=('H3PO4_org','water_org','solvent_aq','SO4_org'), column_widths=[0.5, 0.5], vertical_spacing=0.05,
                     specs=[[{"type": "scene"}, {"type": "scene"}],[{"type": "scene"}, {"type": "scene"}]])

fig_equil2.add_trace(go.Scatter3d(x=data2.H3PO4_aq, y=data2.SO4_aq, z=data2.H3PO4_org, mode='markers', name='H3PO4_org'), 1, 1)
fig_equil2.add_trace(go.Scatter3d(x=data2.H3PO4_aq, y=data2.SO4_aq, z=data2.water_org, mode='markers', name='water_org'), 1, 2)
fig_equil2.add_trace(go.Scatter3d(x=data2.H3PO4_aq, y=data2.SO4_aq, z=data2.solvent_aq, mode='markers', name='solvent_aq'), 2, 1)
fig_equil2.add_trace(go.Scatter3d(x=data2.H3PO4_aq, y=data2.SO4_aq, z=data2.SO4_org, mode='markers', name='SO4_org'), 2, 2)

bat=bat5_1
# H3PO4_org
fig_equil2.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,1], mode='markers', name='Efficiency'), 1, 1)
fig_equil2.add_trace(go.Scatter3d(x=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])), y=np.concatenate((bat.xout_list[:,2], [bat.xin_list[-1,2]])), z=np.concatenate((bat.yin_list[:,1], [bat.yout_list[-1,1]])),
                                mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),
                                                                                                                            np.concatenate((bat.xout_list[:,2], [bat.xin_list[-1,2]])),
                                                                                                                            np.concatenate((bat.yin_list[:,1], [bat.yout_list[-1,1]])))],
                                textposition ='bottom center', name='Operation', marker_color='green'),1,1)

fig_equil2.update_layout(title='', autosize=True,
                  width=980, height=980,
                  margin=dict(l=0, r=0, b=0, t=30),
                  )

fig_equil2.update_layout(
    scene1_zaxis_range=[0,15],
    scene2_zaxis_range=[8,10],
    scene3_zaxis_range=[0,3],
    scene4_zaxis_range=[.05,.1],
    )

fig_equil2.update_scenes(xaxis_title='H3PO4_aq', yaxis_title='SO4_aq', camera_eye=dict(x=1.5, y=-1.5, z=1.5))

fig_equil2.show()

## Rotem washing LLC tests

### data

In [52]:
data=CopyPasteToArray('''
H3PO4_aq	SO4_aq	H3PO4_org	water_org	solvent_aq	SO4_org	water_org-original
0.011	0.0932	0.072	8.69	1.70	0.0186	12.09
10.325	0.0017	0.229	10.66	1.52	0.02	10.66
10.380	0.0990	0.269	8.31	1.50	0.0208	10.41
19.821	0.0031	0.635	11.3	1.34	0.01884	11.3
19.710	0.0928	0.773	10.36	1.32	0.0195	12.34
28.710	0.0057	1.435	11.96	1.28	0.01978	11.96
27.882	0.0858	1.325	9.7	1.34	0.0222	11.1
35.611	0.0071	2.871	11.94	1.28	0.036	11.94
35.887	0.0846	2.981	12.02	1.24	0.0374	12.6
43.065	0.0082	5.328	12.12	1.28	0.057	12.12
43.065	0.0802	5.604	10.38	1.06	0.0608	11.7
49.966	0.0074	8.723	12.28	1.28	0.0872	12.28
0.017	0.1540	0.042	11.48	1.46	0.0164	13.28
4.831	0.0020	0.146	12.7	1.78	0.01302	12.6
4.941	0.1078	0.173	12.06	1.66	0.0139	11.84
19.600	0.0033	0.828	11.84	1.38	0.01688	11.42
19.766	0.1120	0.856	12.46	1.38	0.01832	11.2
''')
# data
# data2=pd.DataFrame(data, columns=['H3PO4_aq',	'SO4_aq',	'H3PO4_org',	'water_org',	'solvent_aq',	'SO4_org'])
data3=pd.DataFrame(data[1:], columns=data[0])
data3_names=CopyPasteToArray('''
wp12	wp21	wp22	wp31	wp32	wp41	wp42	wp51	wp52	wp61	wp62	wp71	wp13	ww11	ww12	ww21	ww22
''')

In [53]:
# x_mesh, y_mesh = np.linspace(0, 60, 31), np.linspace(0, 0.2, 31) # expanded x and y extrapolation area observation
x_mesh, y_mesh = np.linspace(0, 50, 31), np.linspace(0, 0.15, 31)
x_mesh, y_mesh = np.meshgrid(x_mesh, y_mesh)
x_mesh3 = x_mesh.flatten().reshape(31*31,1)
y_mesh3 = y_mesh.flatten().reshape(31*31,1)
mesh3=np.concatenate((x_mesh3, y_mesh3), axis=1)
# x_mesh[:5]

In [54]:
a=np.concatenate((np.zeros([len(mesh3),1]),mesh3), axis=1)

In [55]:
mesh_predict_x=np.array([EQUIL_rotem_washing3([row]).xout for row in a])
mesh_predict_y=np.array([EQUIL_rotem_washing3([row]).yout for row in a])
mesh_predics3_1=mesh_predict_y[:,:,1]
mesh_predics3_2=mesh_predict_y[:,:,0]
mesh_predics3_3=mesh_predict_x[:,:,0]
mesh_predics3_4=mesh_predict_y[:,:,2]

### test

In [56]:
EQUIL_rotem_washing3([[2.2,10.38,.099]]).yout

array([[9.02976303, 0.5493118 , 0.01802152]])

In [57]:
test1 = LLC.Stage(90, 29, [10, 14, .07], [0, 0.1, .02], EQUIL_rotem_washing3, eff=.8)#, entrainment_perc=[1,2,3,4], entrainment_comp_in=[[10,10],[5,5]], convergence=1E-4)
test1.runs

3

In [58]:
test1.output()

Oout= 78.32179881063443
yout= [9.60912967 3.76230026 0.03045747]
yout_tag= [9.60912967 1.20287533 0.02057183]  %water_org_equilib, %solubles_equilib
Aout= 40.67820118936556
xout= [ 1.25110892 23.80920178  0.11050305]
equilibrium efficiency= [1.  0.8 0.8]
error= [ 7.39425190e-07 -9.69302553e-04 -2.30061189e-04]
convergence= [-2.05215689e-04 -7.82960672e-04 -8.59080721e-05]


### 6 - Washing1 - water_org model

In [59]:
bat6_1=LLC.Battery(stages_num=5, Oin=90, Ain=29, yin=[10, 14, .07], xin=[0, 0.1, .02], EQUIL=EQUIL_rotem_washing3, eff=.7)
bat6_1.runs

21

In [60]:
table6_1=LLC.BatteryTable(bat6_1).data

Stage 1    Stage 2    Stage 3    Stage 4    Stage 5
Org in, ton/hr   90.000000  80.315656  77.402606  76.362880  75.972655
y1 in, %         10.000000   9.556306   9.657001   9.716974   9.747376
y2 in, %         14.000000   5.219303   1.992958   0.760381   0.281593
y3 in, %          0.070000   0.036196   0.023426   0.018414   0.016422
Aq in, ton/hr    34.016975  31.103606  30.063793  29.673346  29.000000
x1 in, %          1.626419   1.610304   1.602890   1.599657   0.000000
x2 in, %         12.201220   4.825139   1.792163   0.579511   0.100000
x3 in, %          0.067926   0.039113   0.026924   0.021934   0.020000
Org out, ton/hr  80.315643  77.402535  76.362846  75.972510  75.299319
y1 out, %         9.556313   9.657020   9.716978   9.747382   9.761492
y2 out, %         5.219291   1.992907   0.760365   0.281558   0.094268
y3 out, %         0.036196   0.023425   0.018414   0.016422   0.015628
Aq out, ton/hr   43.701332  34.016728  31.103553  30.063717  29.673336
x1 out, %         1.077324   1.626415   1.610303   1.602889   1.599657
x2 out, %        28.737307  12.200321   4.824939   1.791871   0.579477
x3 out, %         0.130512   0.067922   0.039112   0.026923   0.021934

In [61]:
fig_equil6_1 = make_subplots(rows=2, cols=2, subplot_titles=('H3PO4_org','water_org','solvent_aq','SO4_org'), column_widths=[0.5, 0.5], vertical_spacing=0.05,
                     specs=[[{"type": "scene"}, {"type": "scene"}],[{"type": "scene"}, {"type": "scene"}]])

fig_equil6_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.H3PO4_org, mode='markers', name='H3PO4_org'), 1, 1)
fig_equil6_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.water_org, mode='markers', name='water_org'), 1, 2)
fig_equil6_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.solvent_aq, mode='markers', name='solvent_aq'), 2, 1)
fig_equil6_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.SO4_org, mode='markers', name='SO4_org'), 2, 2)

# visib='legendonly'
visib=True
fig_equil6_1.add_trace(go.Scatter3d(x=x_mesh3[:,0], y=y_mesh3[:,0], z=mesh_predics3_1[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),1,1)
fig_equil6_1.add_trace(go.Scatter3d(x=x_mesh3[:,0], y=y_mesh3[:,0], z=mesh_predics3_2[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),1,2)
fig_equil6_1.add_trace(go.Scatter3d(x=x_mesh3[:,0], y=y_mesh3[:,0], z=mesh_predics3_3[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),2,1)
fig_equil6_1.add_trace(go.Scatter3d(x=x_mesh3[:,0], y=y_mesh3[:,0], z=mesh_predics3_4[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),2,2)

bat=bat6_1
# n, row, col =[1,0,2], [1,1,2], [1,2,2] # H3PO4_org, water_org, SO4_org
# for i in range(3):
#   fig_equil6_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,n[i]], mode='markers', marker_color='blue', name='Efficiency'), row[i], col[i])
#   x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,n[i]],[bat.yout_list[-1,n[i]]]))
#   fig_equil6_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),row[i],col[i])

# H3PO4_org
fig_equil6_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,1], mode='markers', marker_color='blue', name='Efficiency'), 1, 1)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,1],[bat.yout_list[-1,1]]))
fig_equil6_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),1,1)
# water_org
fig_equil6_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,0], mode='markers', marker_color='blue', name='Efficiency'), 1, 2)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,0],[bat.yout_list[-1,0]]))
fig_equil6_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),1,2)
# SO4_org
fig_equil6_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,2], mode='markers', marker_color='blue', name='Efficiency'), 2, 2)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,2],[bat.yout_list[-1,2]]))
fig_equil6_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),2,2)

# solvent_aq
fig_equil6_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.xout_list[:,0], mode='markers', marker_color='blue', name='Efficiency'), 2, 1)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.xout_list[:,0],[bat.xin_list[-1,0]])) # aqueous -- different operation line order
fig_equil6_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),2,1)


fig_equil6_1.update_layout(title='', autosize=True,
                  width=980, height=980,
                  margin=dict(l=0, r=0, b=0, t=30),
                  )

fig_equil6_1.update_layout(
    # scene1_zaxis_range=[0,10],
    # scene2_zaxis_range=[10,14],
    # scene3_zaxis_range=[0,3],
    # scene4_zaxis_range=[0,.1],
    )

# fig_equil6_1.update_scenes(xaxis_title='H3PO4_aq', yaxis_title='SO4_aq', camera_eye=dict(x=1.5, y=-1.5, z=1.5))
fig_equil6_1.update_scenes(xaxis_title='H3PO4_aq', yaxis_title='SO4_aq', camera_eye=dict(x=0, y=-2.2, z=0.01))
fig_equil6_1.update_scenes(camera_projection_type="orthographic")

fig_equil6_1.show()

### 7 - Washing2 - water_org=12

In [62]:
# x_mesh, y_mesh = np.linspace(0, 60, 31), np.linspace(0, 0.2, 31) # expanded x and y extrapolation area observation
x_mesh, y_mesh = np.linspace(0, 50, 31), np.linspace(0, 0.15, 31)
x_mesh, y_mesh = np.meshgrid(x_mesh, y_mesh)
x_mesh4 = x_mesh.flatten().reshape(31*31,1)
y_mesh4 = y_mesh.flatten().reshape(31*31,1)
mesh4=np.concatenate((x_mesh4, y_mesh4), axis=1)

In [63]:
a=np.concatenate((np.zeros([len(mesh4),1]),mesh4), axis=1)

In [64]:
mesh_predict_x=np.array([EQUIL_rotem_washing3_2([row]).xout for row in a])
mesh_predict_y=np.array([EQUIL_rotem_washing3_2([row]).yout for row in a])
mesh_predics4_1=mesh_predict_y[:,:,1]
mesh_predics4_2=mesh_predict_y[:,:,0]
mesh_predics4_3=mesh_predict_x[:,:,0]
mesh_predics4_4=mesh_predict_y[:,:,2]

In [65]:
bat7_1=LLC.Battery(stages_num=5, Oin=90, Ain=29, yin=[10, 14, .07], xin=[0, 0.1, .02], EQUIL=EQUIL_rotem_washing3_2, eff=.7)
bat7_1.runs

21

In [66]:
table7_1=LLC.BatteryTable(bat7_1).data

Stage 1    Stage 2    Stage 3    Stage 4    Stage 5
Org in, ton/hr   90.000000  82.794901  79.586005  78.421448  77.976314
y1 in, %         10.000000  12.000000  12.000000  12.000000  12.000000
y2 in, %         14.000000   5.267622   2.018177   0.773599   0.288009
y3 in, %          0.070000   0.036412   0.023539   0.018473   0.016451
Aq in, ton/hr    34.530811  31.321228  30.156551  29.711021  29.000000
x1 in, %          1.627135   1.610703   1.603071   1.599715   0.000000
x2 in, %         12.499448   4.982271   1.859997   0.601322   0.100000
x3 in, %          0.069119   0.039751   0.027203   0.022024   0.020000
Org out, ton/hr  82.794879  79.585875  78.421405  77.976065  77.265306
y1 out, %        12.000000  12.000000  12.000000  12.000000  12.000000
y2 out, %         5.267611   2.018110   0.773583   0.287961   0.096978
y3 out, %         0.036412   0.023538   0.018473   0.016450   0.015640
Aq out, ton/hr   41.735931  34.530254  31.321151  30.156404  29.711008
x1 out, %         1.030205   1.627130   1.610702   1.603069   1.599714
x2 out, %        30.081651  12.498270   4.982073   1.859589   0.601286
x3 out, %         0.135902   0.069113   0.039750   0.027201   0.022023

In [67]:
fig_equil7_1 = make_subplots(rows=2, cols=2, subplot_titles=('H3PO4_org','water_org','solvent_aq','SO4_org'), column_widths=[0.5, 0.5], vertical_spacing=0.05,
                     specs=[[{"type": "scene"}, {"type": "scene"}],[{"type": "scene"}, {"type": "scene"}]])

fig_equil7_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.H3PO4_org, mode='markers', name='H3PO4_org'), 1, 1)
fig_equil7_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.water_org, mode='markers', name='water_org'), 1, 2)
fig_equil7_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.solvent_aq, mode='markers', name='solvent_aq'), 2, 1)
fig_equil7_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.SO4_org, mode='markers', name='SO4_org'), 2, 2)

# visib='legendonly'
visib=True
fig_equil7_1.add_trace(go.Scatter3d(x=x_mesh4[:,0], y=y_mesh4[:,0], z=mesh_predics4_1[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),1,1)
fig_equil7_1.add_trace(go.Scatter3d(x=x_mesh4[:,0], y=y_mesh4[:,0], z=mesh_predics4_2[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),1,2)
fig_equil7_1.add_trace(go.Scatter3d(x=x_mesh4[:,0], y=y_mesh4[:,0], z=mesh_predics4_3[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),2,1)
fig_equil7_1.add_trace(go.Scatter3d(x=x_mesh4[:,0], y=y_mesh4[:,0], z=mesh_predics4_4[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),2,2)

bat=bat7_1
# n, row, col =[1,0,2], [1,1,2], [1,2,2] # H3PO4_org, water_org, SO4_org
# for i in range(3):
#   fig_equil6_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,n[i]], mode='markers', marker_color='blue', name='Efficiency'), row[i], col[i])
#   x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,n[i]],[bat.yout_list[-1,n[i]]]))
#   fig_equil6_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),row[i],col[i])

# H3PO4_org
fig_equil7_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,1], mode='markers', marker_color='blue', name='Efficiency'), 1, 1)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,1],[bat.yout_list[-1,1]]))
fig_equil7_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),1,1)
# water_org
fig_equil7_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,0], mode='markers', marker_color='blue', name='Efficiency'), 1, 2)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,0],[bat.yout_list[-1,0]]))
fig_equil7_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),1,2)
# SO4_org
fig_equil7_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,2], mode='markers', marker_color='blue', name='Efficiency'), 2, 2)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,2],[bat.yout_list[-1,2]]))
fig_equil7_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),2,2)

# solvent_aq
fig_equil7_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.xout_list[:,0], mode='markers', marker_color='blue', name='Efficiency'), 2, 1)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.xout_list[:,0],[bat.xin_list[-1,0]])) # aqueous -- different operation line order
fig_equil7_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),2,1)


fig_equil7_1.update_layout(title='', autosize=True,
                  width=980, height=980,
                  margin=dict(l=0, r=0, b=0, t=30),
                  )

fig_equil7_1.update_layout(
    # scene1_zaxis_range=[0,10],
    # scene2_zaxis_range=[10,14],
    # scene3_zaxis_range=[0,3],
    # scene4_zaxis_range=[0,.1],
    )

# fig_equil7_1.update_scenes(xaxis_title='H3PO4_aq', yaxis_title='SO4_aq', camera_eye=dict(x=1.5, y=-1.5, z=1.5))
fig_equil7_1.update_scenes(xaxis_title='H3PO4_aq', yaxis_title='SO4_aq', camera_eye=dict(x=0, y=-2.2, z=0.01))
fig_equil7_1.update_scenes(camera_projection_type="orthographic")

fig_equil7_1.show()

### 8 - Washing3

Plant data

In [122]:
PS_P2O5=11.6
WS_P2O5=0.5
W_flow=23.4
Prod_flow=48.4 # =36.7*1.32
Prod_P2O5=37.6

PS_flow=(Prod_flow*Prod_P2O5+WS_P2O5*(W_flow-Prod_flow))/(PS_P2O5-WS_P2O5)
WS_flow=PS_flow+W_flow-Prod_flow
P2O5_recovery=Prod_flow*Prod_P2O5/(PS_flow*PS_P2O5)
print ('Purified solvent flow =',f"{PS_flow:.1f}",'ton/hr,  ', 'Washed solvent flow =',f"{WS_flow:.1f}",'ton/hr  ', 'P2O5 recovery =',f"{P2O5_recovery:.1%}")

Purified solvent flow = 162.8 ton/hr,   Washed solvent flow = 137.8 ton/hr   P2O5 recovery = 96.4%


In [123]:
summary_table8=pd.DataFrame([PS_flow,PS_P2O5,WS_flow,WS_P2O5,W_flow,Prod_flow,Prod_P2O5,f"{P2O5_recovery:.1%}",6,'---', '---'],
                        index=['PS_flow','PS_P2O5','WS_flow','WS_P2O5','W_flow','Prod_flow','Prod_P2O5','P2O5_recovery','Stages_num','Efficiency','Equilibrium'],
                        columns=['Plant data'])
summary_table8

Plant data
PS_flow        162.823423
PS_P2O5              11.6
WS_flow        137.823423
WS_P2O5               0.5
W_flow               23.4
Prod_flow            48.4
Prod_P2O5            37.6
P2O5_recovery       96.4%
Stages_num              6
Efficiency            ---
Equilibrium           ---

In [148]:
bat8_1=LLC.Battery(stages_num=6, Oin=PS_flow, Ain=W_flow, yin=[12,PS_P2O5/71*98,.07], xin=[0,0,.02], EQUIL=EQUIL_rotem_washing3_2, eff=.61, convergence=1E-2, entrainment_perc_out=[2.5,0])
bat8_1.runs

28

In [149]:
bat=bat8_1
summary_table8['Model data-0.75-3']=[bat.Oin,bat.yin[1]/98*71,bat.Oout,bat.yout[1]/98*71,bat.Ain,bat.Aout,bat.xout[1]/98*71,f"{bat.Aout*bat.xout[1]/(bat.Oin*bat.yin[1]):.1%}", f"{bat.stages_num:.0f}", bat.eff[0,1], str(bat.EQUIL)[17:-2]]
summary_table8

Plant data       Model data-0.75-3
PS_flow        162.823423              162.823423
PS_P2O5              11.6                    11.6
WS_flow        137.823423              133.453261
WS_P2O5               0.5                0.510279
W_flow               23.4                    23.4
Prod_flow            48.4               49.557207
Prod_P2O5            37.6               37.212375
P2O5_recovery       96.4%                   97.6%
Stages_num              6                       6
Efficiency            ---                    0.61
Equilibrium           ---  EQUIL_rotem_washing3_2

In [150]:
table8_1=LLC.BatteryTable(bat8_1).data

Stage 1     Stage 2     Stage 3     Stage 4     Stage 5  \
Org in, ton/hr   162.823423  153.536354  146.776843  140.575787  137.063643   
y1 in, %          12.000000   12.000000   12.000000   12.000000   12.000000   
y2 in, %          16.011268   11.831304    8.395087    4.840884    2.651842   
y3 in, %           0.070000    0.083478    0.073345    0.049894    0.032657   
Aq in, ton/hr     44.116777   37.076005   30.787932   27.038350   25.046798   
x1 in, %           0.233547    0.427729    0.944012    1.486398    1.639685   
x2 in, %          43.870059   34.805370   22.865134   12.201418    4.968683   
x3 in, %           0.264327    0.256806    0.186106    0.103992    0.052276   
Org out, ton/hr  153.544384  146.734789  140.586833  137.005023  135.101736   
y1 out, %         12.000000   12.000000   12.000000   12.000000   12.000000   
y2 out, %         11.835472    8.370018    4.867797    2.625988    1.427495   
y3 out, %          0.083515    0.073121    0.050135    0.032452    0.023979   
Aq out, ton/hr    49.557207   44.047608   37.132692   30.698383   27.057754   
x1 out, %          0.384959    0.235403    0.424647    0.956427    1.482511   
x2 out, %         51.363560   43.789749   34.896931   22.651167   12.270658   
x3 out, %          0.197749    0.264229    0.257143    0.184101    0.104610   

                    Stage 6  
Org in, ton/hr   135.042815  
y1 in, %          12.000000  
y2 in, %           1.420486  
y3 in, %           0.023930  
Aq in, ton/hr     23.400000  
x1 in, %           0.000000  
x2 in, %           0.000000  
x3 in, %           0.020000  
Org out, ton/hr  133.453261  
y1 out, %         12.000000  
y2 out, %          0.704329  
y3 out, %          0.019361  
Aq out, ton/hr    25.029293  
x1 out, %          1.638857  
x2 out, %          4.900775  
x3 out, %          0.051716

In [151]:
## P2O5
bat=bat8_1
summary_table=summary_table8
fig8_1 = go.Figure()
n=1 #H3PO4
fig8_1.add_trace(go.Scatter(x=[0,summary_table['Plant data'].loc['Prod_P2O5']], y=[summary_table['Plant data'].loc['WS_P2O5'],summary_table['Plant data'].loc['PS_P2O5']], name='Plant data', marker_color='orange'))
fig8_1.add_trace(go.Scatter(x=np.concatenate((bat.xout_list[:,n]*71/98, [bat.xin_list[-1,n]/98*71])), y=np.concatenate((bat.yin_list[:,n]/98*71, [bat.yout_list[-1,n]/98*71])), mode = "markers+lines+text",
                          text= ['({:.2f},{:.2f})'.format(a,b) for a,b in zip(np.concatenate((bat.xout_list[:,n]/98*71, [bat.xin_list[-1,n]/98*71])),np.concatenate((bat.yin_list[:,n]/98*71, [bat.yout_list[-1,n]/98*71])))],
                          textposition ='bottom center', name='Model data', marker_color='green'))
fig8_1.add_trace(go.Scatter(x=bat.xout_list[:,n]/98*71, y=bat.yout_list[:,n]/98*71, name='Efficiency', marker_color='blue'))
fig8_1.add_trace(go.Scatter(x=bat.xout_list[:,n]/98*71, y=bat.yout_tag_list[:,n]/98*71, name='Equilibrium', marker_color='black'))

fig8_1.update_xaxes(title_text="%P2O5 aq")#, range=[0.5, 2])
fig8_1.update_yaxes(title_text="%P2O5 org")#, range=[0.5, 2])
fig8_1.update_layout(title='', width=1200, height=600,)
fig8_1.show()

In [103]:
# x_mesh, y_mesh = np.linspace(0, 60, 31), np.linspace(0, 0.2, 31) # expanded x and y extrapolation area observation
x_mesh, y_mesh = np.linspace(0, 50, 31), np.linspace(0, 0.15, 31)
x_mesh, y_mesh = np.meshgrid(x_mesh, y_mesh)
x_mesh4 = x_mesh.flatten().reshape(31*31,1)
y_mesh4 = y_mesh.flatten().reshape(31*31,1)
mesh4=np.concatenate((x_mesh4, y_mesh4), axis=1)

In [104]:
a=np.concatenate((np.zeros([len(mesh4),1]),mesh4), axis=1)

In [105]:
mesh_predict_x=np.array([EQUIL_rotem_washing3_2([row]).xout for row in a])
mesh_predict_y=np.array([EQUIL_rotem_washing3_2([row]).yout for row in a])
mesh_predics4_1=mesh_predict_y[:,:,1]
mesh_predics4_2=mesh_predict_y[:,:,0]
mesh_predics4_3=mesh_predict_x[:,:,0]
mesh_predics4_4=mesh_predict_y[:,:,2]

In [106]:
fig_equil8_1 = make_subplots(rows=2, cols=2, subplot_titles=('H3PO4_org','water_org','solvent_aq','SO4_org'), column_widths=[0.5, 0.5], vertical_spacing=0.05,
                     specs=[[{"type": "scene"}, {"type": "scene"}],[{"type": "scene"}, {"type": "scene"}]])

fig_equil8_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.H3PO4_org, mode='markers', name='H3PO4_org'), 1, 1)
fig_equil8_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.water_org, mode='markers', name='water_org'), 1, 2)
fig_equil8_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.solvent_aq, mode='markers', name='solvent_aq'), 2, 1)
fig_equil8_1.add_trace(go.Scatter3d(x=data3.H3PO4_aq, y=data3.SO4_aq, z=data3.SO4_org, mode='markers', name='SO4_org'), 2, 2)

# visib='legendonly'
visib=True
fig_equil8_1.add_trace(go.Scatter3d(x=x_mesh4[:,0], y=y_mesh4[:,0], z=mesh_predics4_1[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),1,1)
fig_equil8_1.add_trace(go.Scatter3d(x=x_mesh4[:,0], y=y_mesh4[:,0], z=mesh_predics4_2[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),1,2)
fig_equil8_1.add_trace(go.Scatter3d(x=x_mesh4[:,0], y=y_mesh4[:,0], z=mesh_predics4_3[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),2,1)
fig_equil8_1.add_trace(go.Scatter3d(x=x_mesh4[:,0], y=y_mesh4[:,0], z=mesh_predics4_4[:,0], mode='markers',marker_color='green', marker_size=0.5, name='Equilibrium surface', visible=visib),2,2)

bat=bat8_1
# n, row, col =[1,0,2], [1,1,2], [1,2,2] # H3PO4_org, water_org, SO4_org
# for i in range(3):
#   fig_equil6_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,n[i]], mode='markers', marker_color='blue', name='Efficiency'), row[i], col[i])
#   x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,n[i]],[bat.yout_list[-1,n[i]]]))
#   fig_equil6_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),row[i],col[i])

# H3PO4_org
fig_equil8_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,1], mode='markers', marker_color='blue', name='Efficiency'), 1, 1)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,1],[bat.yout_list[-1,1]]))
fig_equil8_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),1,1)
# water_org
fig_equil8_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,0], mode='markers', marker_color='blue', name='Efficiency'), 1, 2)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,0],[bat.yout_list[-1,0]]))
fig_equil8_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),1,2)
# SO4_org
fig_equil8_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.yout_list[:,2], mode='markers', marker_color='blue', name='Efficiency'), 2, 2)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.yin_list[:,2],[bat.yout_list[-1,2]]))
fig_equil8_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),2,2)

# solvent_aq
fig_equil8_1.add_trace(go.Scatter3d(x=bat.xout_list[:,1], y=bat.xout_list[:,2], z=bat.xout_list[:,0], mode='markers', marker_color='blue', name='Efficiency'), 2, 1)
x,y,z=np.concatenate((bat.xout_list[:,1], [bat.xin_list[-1,1]])),np.concatenate((bat.xout_list[:,2],[bat.xin_list[-1,2]])), np.concatenate((bat.xout_list[:,0],[bat.xin_list[-1,0]])) # aqueous -- different operation line order
fig_equil8_1.add_trace(go.Scatter3d(x=x, y=y, z=z, mode = "markers+lines+text", text= ['({:.2f},{:.2f},{:.2f})'.format(a,b,c) for a,b,c in zip(x,y,z)], textposition ='bottom center', name='Operation', marker_color='green'),2,1)


fig_equil8_1.update_layout(title='', autosize=True,
                  width=980, height=980,
                  margin=dict(l=0, r=0, b=0, t=30),
                  )

fig_equil8_1.update_layout(
    # scene1_zaxis_range=[0,10],
    # scene2_zaxis_range=[10,14],
    # scene3_zaxis_range=[0,3],
    # scene4_zaxis_range=[0,.1],
    )

# fig_equil8_1.update_scenes(xaxis_title='H3PO4_aq', yaxis_title='SO4_aq', camera_eye=dict(x=1.5, y=-1.5, z=1.5))
fig_equil8_1.update_scenes(xaxis_title='H3PO4_aq', yaxis_title='SO4_aq', camera_eye=dict(x=0, y=-2.2, z=0.01))
fig_equil8_1.update_scenes(camera_projection_type="orthographic")

fig_equil8_1.show()

### 9 - Washing4 - minimize

Plant data

In [154]:
PS_P2O5=11.6
WS_P2O5=0.5
W_flow=23.4
Prod_flow=48.4 # =36.7*1.32
Prod_P2O5=37.6

PS_flow=(Prod_flow*Prod_P2O5+WS_P2O5*(W_flow-Prod_flow))/(PS_P2O5-WS_P2O5)
WS_flow=PS_flow+W_flow-Prod_flow
P2O5_recovery=Prod_flow*Prod_P2O5/(PS_flow*PS_P2O5)
print ('Purified solvent flow =',f"{PS_flow:.1f}",'ton/hr,  ', 'Washed solvent flow =',f"{WS_flow:.1f}",'ton/hr  ', 'P2O5 recovery =',f"{P2O5_recovery:.1%}")

Purified solvent flow = 162.8 ton/hr,   Washed solvent flow = 137.8 ton/hr   P2O5 recovery = 96.4%


In [153]:
summary_table9=pd.DataFrame([PS_flow,PS_P2O5,WS_flow,WS_P2O5,W_flow,Prod_flow,Prod_P2O5,f"{P2O5_recovery:.1%}",6,'---', '---'],
                        index=['PS_flow','PS_P2O5','WS_flow','WS_P2O5','W_flow','Prod_flow','Prod_P2O5','P2O5_recovery','Stages_num','Efficiency','Equilibrium'],
                        columns=['Plant data'])
summary_table9

Plant data
PS_flow        162.823423
PS_P2O5              11.6
WS_flow        137.823423
WS_P2O5               0.5
W_flow               23.4
Prod_flow            48.4
Prod_P2O5            37.6
P2O5_recovery       96.4%
Stages_num              6
Efficiency            ---
Equilibrium           ---

In [ ]:
bat9_1=LLC.Battery(stages_num=6, Oin=PS_flow, Ain=W_flow, yin=[12,PS_P2O5/71*98,.07], xin=[0,0,.02], EQUIL=EQUIL_rotem_washing3_2, eff=.61, convergence=1E-2, entrainment_perc_out=[2.5,0])
bat9_1.runs

28

In [ ]:
bat=bat9_1
summary_table9['Model data-0.75-3']=[bat.Oin,bat.yin[1]/98*71,bat.Oout,bat.yout[1]/98*71,bat.Ain,bat.Aout,bat.xout[1]/98*71,f"{bat.Aout*bat.xout[1]/(bat.Oin*bat.yin[1]):.1%}", f"{bat.stages_num:.0f}", bat.eff[0,1], str(bat.EQUIL)[17:-2]]
summary_table9

Plant data       Model data-0.75-3
PS_flow        162.823423              162.823423
PS_P2O5              11.6                    11.6
WS_flow        137.823423              133.453261
WS_P2O5               0.5                0.510279
W_flow               23.4                    23.4
Prod_flow            48.4               49.557207
Prod_P2O5            37.6               37.212375
P2O5_recovery       96.4%                   97.6%
Stages_num              6                       6
Efficiency            ---                    0.61
Equilibrium           ---  EQUIL_rotem_washing3_2

In [159]:
def P2O5_calc(x):
  PS_P2O5=11.6
  WS_P2O5=0.5
  W_flow=23.4
  Prod_flow=48.4 # =36.7*1.32
  Prod_P2O5=37.6
  PS_flow=(Prod_flow*Prod_P2O5+WS_P2O5*(W_flow-Prod_flow))/(PS_P2O5-WS_P2O5)
  eff, entrain = x[0], x[1]
  bat=LLC.Battery(stages_num=6, Oin=PS_flow, Ain=W_flow, yin=[12,PS_P2O5/71*98,.07], xin=[0,0,.02], EQUIL=EQUIL_rotem_washing3_2, eff=eff, convergence=1E-2, entrainment_perc_out=[entrain,0])
  error1=abs(WS_P2O5-bat.yout[1])/WS_P2O5*1E4
  error2=abs(Prod_P2O5-bat.xout[1])/Prod_P2O5*1E4
  print ('. ')
  return error1+error2

In [165]:
bnds=((0.5,1),(0,5))
sol3=optimize.minimize(P2O5_calc, [0.9, 3], bounds=bnds, options={'maxiter':10, 'disp':True}, tol=1, method=’Newton-CG’)

SyntaxError: ignored

In [164]:
print (sol3.fun, sol3.x)

1.1586936183377738 [0.89999996 2.99999966]
